export const recipes = [
  {
    id: "1",
    name: "Spaghetti Bolognese",
    cuisine: "Italian",
    img: "https://www.slimmingeats.com/blog/wp-content/uploads/2010/04/spaghetti-bolognese-36-720x720.jpg",
    ingredients: [
      "spaghetti",
      "ground beef",
      "tomatoes",
      "onion",
      "garlic",
      "olive oil",
      "Italian seasoning",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook the spaghetti according to the package instructions.",
      "In a large pan, heat olive oil over medium heat.",
      "Add the onion and garlic, and sauté until translucent.",
      "Add the ground beef and cook until browned.",
      "Stir in the tomatoes, Italian seasoning, salt, and pepper.",
      "Simmer the sauce for 15-20 minutes, stirring occasionally.",
      "Serve the sauce over the cooked spaghetti.",
    ],
  },
  {
    id: "2",
    name: "Chicken Curry",
    cuisine: "Indian",
    img: "https://www.licious.in/blog/wp-content/uploads/2022/12/shutterstock_223265560.jpg",
    ingredients: [
      "chicken",
      "onion",
      "ginger",
      "garlic",
      "tomatoes",
      "curry powder",
      "coconut milk",
      "vegetable oil",
      "salt",
    ],
    instructions: [
      "In a large pan, heat vegetable oil over medium heat.",
      "Add the onion, ginger, and garlic, and sauté until fragrant.",
      "Add the chicken pieces and cook until browned.",
      "Stir in the tomatoes, curry powder, and salt.",
      "Simmer the curry for 20-25 minutes, until the chicken is cooked through.",
      "Pour in the coconut milk and simmer for an additional 5 minutes.",
      "Serve the chicken curry with rice or naan bread.",
    ],
  },
  {
    id: "3",
    name: "Chocolate Chip Cookies",
    cuisine: "American",
    img: "https://www.shugarysweets.com/wp-content/uploads/2020/05/chocolate-chip-cookies-recipe.jpg",
    ingredients: [
      "butter",
      "granulated sugar",
      "brown sugar",
      "eggs",
      "vanilla extract",
      "all-purpose flour",
      "baking soda",
      "salt",
      "chocolate chips",
      "chopped nuts (optional)",
    ],
    instructions: [
      "Preheat the oven to 375°F (190°C).",
      "In a large bowl, cream together the butter, granulated sugar, and brown sugar until light and fluffy.",
      "Beat in the eggs, one at a time, then stir in the vanilla extract.",
      "In a separate bowl, whisk together the flour, baking soda, and salt.",
      "Gradually add the dry ingredients to the wet ingredients and mix until just combined.",
      "Stir in the chocolate chips and chopped nuts (if using).",
      "Drop rounded tablespoons of dough onto ungreased baking sheets.",
      "Bake for 9 to 11 minutes, or until the edges are golden brown.",
      "Allow the cookies to cool on the baking sheets for a few minutes, then transfer them to wire racks to cool completely.",
    ],
  },
];
